-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 18:22:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema partsco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema partsco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `partsco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `partsco` ;

-- -----------------------------------------------------
-- Table `partsco`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`articulos` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock_max` INT NOT NULL,
  `stock_min` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idarticulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`descuentos` (
  `iddescuentos` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddescuentos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `partsco`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`ventas` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATE NOT NULL,
  `total_venta` INT NOT NULL,
  `num_factura` INT NOT NULL,
  `estado_venta` TINYINT NOT NULL,
  `impuestos` DECIMAL(4,2) NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_ventas_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `partsco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`detalles_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`detalles_ventas` (
  `iddetalles_venta` INT NOT NULL AUTO_INCREMENT,
  `precio_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `ventas_idventa` INT NOT NULL,
  `articulos_idarticulo` INT NOT NULL,
  PRIMARY KEY (`iddetalles_venta`),
  INDEX `fk_detalles_ventas_ventas1_idx` (`ventas_idventa` ASC) VISIBLE,
  INDEX `fk_detalles_ventas_articulos1_idx` (`articulos_idarticulo` ASC) VISIBLE,
  CONSTRAINT `fk_detalles_ventas_ventas1`
    FOREIGN KEY (`ventas_idventa`)
    REFERENCES `partsco`.`ventas` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_ventas_articulos1`
    FOREIGN KEY (`articulos_idarticulo`)
    REFERENCES `partsco`.`articulos` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`sesiones` (
  `idsesion` INT NOT NULL AUTO_INCREMENT,
  `fecha_sesion` DATE NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `fk_sesiones_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_sesiones_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `partsco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
