-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 12:30:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema partsco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema partsco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `partsco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `partsco` ;

-- -----------------------------------------------------
-- Table `partsco`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`articulos` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock_max` INT NOT NULL,
  `stock_min` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idarticulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`descuentos` (
  `iddescuentos` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddescuentos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `partsco`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`solicitudes` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATE NOT NULL,
  `valor_total` INT NOT NULL,
  `num_factura` INT NOT NULL,
  `estado_solicitud` TINYINT NOT NULL,
  `impuestos` DECIMAL(4,2) NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitudes_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudes_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `partsco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`detalles_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`detalles_solicitudes` (
  `iddetalles_solicitud` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `articulos_idarticulo` INT NOT NULL,
  `solicitudes_idsolicitud` INT NOT NULL,
  PRIMARY KEY (`iddetalles_solicitud`),
  INDEX `fk_detalles_solicitudes_articulos1_idx` (`articulos_idarticulo` ASC) VISIBLE,
  INDEX `fk_detalles_solicitudes_solicitudes1_idx` (`solicitudes_idsolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_detalles_solicitudes_articulos1`
    FOREIGN KEY (`articulos_idarticulo`)
    REFERENCES `partsco`.`articulos` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_solicitudes_solicitudes1`
    FOREIGN KEY (`solicitudes_idsolicitud`)
    REFERENCES `partsco`.`solicitudes` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partsco`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partsco`.`sesiones` (
  `idsesion` INT NOT NULL AUTO_INCREMENT,
  `fecha_sesion` DATE NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `fk_sesiones_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_sesiones_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `partsco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
